# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: casaos-message-bus
before:
  hooks:
    - go generate
    - go mod tidy
    - go test -v ./...
builds:
  - id: casaos-message-bus-amd64
    binary: build/sysroot/usr/bin/casaos-message-bus
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
    goos:
      - linux
    goarch:
      - amd64
  - id: casaos-message-bus-arm64
    binary: build/sysroot/usr/bin/casaos-message-bus
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
    goos:
      - linux
    goarch:
      - arm64
  - id: casaos-message-bus-arm-7
    binary: build/sysroot/usr/bin/casaos-message-bus
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
  - id: casaos-message-bus-migration-tool-amd64
    binary: build/sysroot/usr/bin/casaos-message-bus-migration-tool
    main: ./cmd/migration-tool
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
    goos:
      - linux
    goarch:
      - amd64
  - id: casaos-message-bus-migration-tool-arm64
    binary: build/sysroot/usr/bin/casaos-message-bus-migration-tool
    main: ./cmd/migration-tool
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
    goos:
      - linux
    goarch:
      - arm64
  - id: casaos-message-bus-migration-tool-arm-7
    binary: build/sysroot/usr/bin/casaos-message-bus-migration-tool
    main: ./cmd/migration-tool
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
archives:
  - name_template: "{{ .Os }}-{{ .Arch }}-{{ .ProjectName }}-v{{ .Version }}"
    id: casaos-message-bus
    builds:
      - casaos-message-bus-amd64
      - casaos-message-bus-arm64
      - casaos-message-bus-arm-7
    replacements:
      arm: arm-7
    files:
      - build/**/*
  - name_template: "{{ .Os }}-{{ .Arch }}-{{ .ProjectName }}-migration-tool-v{{ .Version }}"
    id: casaos-message-bus-migration-tool
    builds:
      - casaos-message-bus-migration-tool-amd64
      - casaos-message-bus-migration-tool-arm64
      - casaos-message-bus-migration-tool-arm-7
    replacements:
      arm: arm-7
    files:
      - build/sysroot/etc/**/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: IceWhaleTech
    name: CasaOS-MessageBus
  draft: true
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
